dataset:
  # dataset name
  decoder: 'libfm'
  num_workers: 4
  paths:
    train: '../data/MovieLens/ml-tag/ml-tag.train.libfm'
    valid: '../data/MovieLens/ml-tag/ml-tag.validation.libfm'
    test: '../data/MovieLens/ml-tag/ml-tag.test.libfm'

model:
  name: 'DeepFM'
  loss_type: 'log_loss'  # ['square_loss', 'log_loss']
  optimizer: 'Adagrad'  # ['Adagrad', 'Adam', 'SGD', 'Momentum']
  activation_function: 'relu'  # ['relu', 'sigmoid', 'tanh', 'identity']
  epochs: 100
  batch_norm: True  # use batch_norm or not
  save: True  # save model or not
  model_path: '../saved/DeepFM/'
  gpu: '0'  # gpu ID
  load: True
  evaluation: True


  hyper_params:
    learning_rate: 0.05
    batch_size: 2  # batch size for training
    embedding_size: 64
    dropout_fm: [0.5, 0.5]  # dropout rate for FM
    dropout_deep: [0.5, 0.5]  # dropout rate for MLP
    deep_layers: [64, 64]  # size of layers in MLP model
    lambda: 0.00  # regularizer for deep layers and prediction layers

evaluation: 'RMSE'  # []


