dataset:
  # dataset name
  decoder: 'libfm'
  num_workers: 4
  paths:
    train: '../data/MovieLens/ml-tag/ml-tag.train.libfm'
    valid: '../data/MovieLens/ml-tag/ml-tag.validation.libfm'
    test: '../data/MovieLens/ml-tag/ml-tag.test.libfm'

model:
  name: 'DeepFM'
  loss_type: 'square_loss'
  optimizer: 'Adam'  # ['Adagrad', 'Adam', 'SGD', 'Momentum']
  activation_function: 'relu'  # ['relu', 'sigmoid', 'tanh', 'identity']
  epochs: 100
  batch_norm: True  # use batch_norm or not
  save: True  # save model or not
  model_path: '../saved/DeepFM/'
  gpu: '0'  # gpu ID
  load: True
  evaluation: True


  hyper_params:
    learning_rate: 0.001
    batch_size: 256  # batch size for training
    embedding_size: 8
    dropout_fm: [1.0, 1.0]  # dropout rate for FM
    dropout_deep: [0.5, 0.5, 0.5]  # dropout rate for MLP, always 1 more integer than deep_layers
    deep_layers: [32, 32]  # size of layers in MLP model
    batch_norm_decay: 0.995
    lambda: 0.01  # regularizer for bilinear layers

evaluation: 'RMSE'  # []


