tag: 'automotive_4'
dataset:
  decoder: 'libfm'
  num_workers: 4
  batch_size: 100  # batch size for training
  bipartite: True  # recommendation in bipartite graph
  paths:
    train: '/home/share/yinxiangkun/libfm/data/ranking/automotive/automotive.train.libfm'
    test: '/home/share/yinxiangkun/libfm/data/ranking/automotive/automotive.test.libfm'

model:
  name: 'NGCF'
  loss_type: 'square_loss'
  optimizer: 'Adam'  # ['Adagrad', 'Adam', 'SGD', 'Momentum']
  learning_rate: 0.001
  epochs: 30
  steps_per_checkpoint: 500
  save: True  # save model or not
  model_path: '/home/share/yinxiangkun/saved/ranking/NGCF/'
  gpu: '0'  # gpu ID
  load: False
  evaluation: True

  hyper_params:
    activation_function: 'leakyrelu'  # ['relu', 'sigmoid', 'tanh', 'leakyrelu']
    normalized: True
    dropout: [0.1, 0.1, 0.1]  # dropout rate for each GNN layer
    embedding_size: 64  # predictive factors numbers in the model
    layers: [128, 96, 64]  # size of layers in GNN layers
    lambda: 0.0  # regularizer for bilinear layers

task: 'ranking'  # ['rating', 'ranking']
