dataset:
  # dataset name
  decoder: 'libfm'
  num_workers: 4
  paths:
    train: '../data/MovieLens/ml-tag/ml-tag.train.libfm'
    valid: '../data/MovieLens/ml-tag/ml-tag.validation.libfm'
    test: '../data/MovieLens/ml-tag/ml-tag.test.libfm'

model:
  name: 'XDeepFM'
  loss_type: 'square_loss'
  optimizer: 'Adagrad'  # ['Adagrad', 'Adam', 'SGD', 'Momentum']
  deep_act: 'relu'  # ['relu', 'sigmoid', 'tanh']
  cin_act: 'relu'  # ['relu', 'sigmoid', 'tanh']
  epochs: 100
  batch_norm: True  # use batch_norm or not
  cin_split_half: False
  save: True  # save model or not
  model_path: '../saved/DeepFM/'
  gpu: '0'  # gpu ID
  load: True
  evaluation: True


  hyper_params:
    field_size: 3  # field of features
    learning_rate: 0.05
    batch_size: 2  # batch size for training
    embedding_size: 64
    deep_layers: [64, 64]  # size of layers in MLP model
    cin_layers: [64, 32]
    dropout_deep: [0.5, 0.5]
    lambda: 0.001  # regularizer for deep layers and prediction layers

evaluation: 'RMSE'  # []


